Granite.HyperTextView
elementary/calendar pull request #728
Opened 2021-12-01 09:51 UTC by marbetschar

Uses `Granite.HyperTextView` for the comment textview of an event. This allows to Ctrl + Click on an existing hyperlink in the event description.

Makes https://github.com/elementary/calendar/pull/692 obsolete.

2021-12-01 21:56 UTC, danrabbit approved these changes

2021-12-01 21:57 UTC, danrabbit requested changes
Can you bump the granite requirement in the README and add a line to appdata as well please? :)

2021-12-02 08:21 UTC, marbetschar commented
Sure thing, thanks for the reminder! :)

2021-12-02 21:45 UTC, danrabbit approved these changes

2021-12-02 21:45 UTC, merged